/* Life OS — calendar export.
 *
 * The honest way to get this into someone's existing calendar. An .ics file
 * with weekly recurring events imports into Google Calendar, Apple Calendar
 * and Outlook without an OAuth flow, a backend, or a token to leak.
 *
 * Deliberately imports into a *separate* calendar rather than syncing: Life OS
 * should never be able to touch or delete anything already in your diary.
 */
(function (root) {
  var LifeOS = (root.LifeOS = root.LifeOS || {});

  /* When each slot starts. Rough by design — the point is a shape for the day,
   * not a claim about when you specifically get up. */
  var SLOT_TIME = {
    morning: [7, 0],
    workday: [9, 30],
    evening: [18, 30],
    night:   [22, 0]
  };
  var BYDAY = ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'];

  function pad(n) { return n < 10 ? '0' + n : String(n); }

  /* UTC for the file's own timestamp — this one is a real instant. */
  function stampUTC(d) {
    return d.getUTCFullYear() + pad(d.getUTCMonth() + 1) + pad(d.getUTCDate()) + 'T' +
           pad(d.getUTCHours()) + pad(d.getUTCMinutes()) + '00Z';
  }

  /* Events use *floating* local time — no Z, no TZID. A 7am habit should stay
   * at 7am after the clocks change, and should still read 7am if you move.
   * Pinning these to UTC would silently shift every recurrence by an hour
   * twice a year. */
  function stamp(d) {
    return d.getFullYear() + pad(d.getMonth() + 1) + pad(d.getDate()) + 'T' +
           pad(d.getHours()) + pad(d.getMinutes()) + '00';
  }

  function local(d, h, m) {
    return new Date(d.getFullYear(), d.getMonth(), d.getDate(), h, m, 0);
  }

  /* RFC 5545 wants CRLF, escaped separators, and lines folded at 75 octets. */
  function esc(t) {
    return String(t).replace(/\\/g, '\\\\').replace(/;/g, '\;')
                    .replace(/,/g, '\\,').replace(/\n/g, '\\n');
  }

  function fold(line) {
    if (line.length <= 74) return line;
    var out = line.slice(0, 74), rest = line.slice(74);
    while (rest.length > 73) { out += '\r\n ' + rest.slice(0, 73); rest = rest.slice(73); }
    return out + '\r\n ' + rest;
  }

  function build(plan, opts) {
    opts = opts || {};
    var weeks = opts.weeks || 12;
    var monday = LifeOS.planner.mondayOf(new Date());
    var now = new Date();
    var lines = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Life OS//Prototype//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:Life OS',
      'X-WR-CALDESC:Generated by Life OS. Safe to delete — it touches nothing else.'
    ];

    var count = 0;
    for (var dayIdx = 0; dayIdx < 7; dayIdx++) {
      LifeOS.SLOTS.forEach(function (slot) {
        var entries = plan.calendar[dayIdx][slot.key];
        if (!entries || !entries.length) return;

        entries.forEach(function (e, i) {
          var t = SLOT_TIME[slot.key] || [12, 0];
          // stagger items in the same slot so they do not stack on top of each other
          var start = local(new Date(monday.getTime() + dayIdx * 86400000), t[0], t[1]);
          start = new Date(start.getTime() + i * 15 * 60000);
          var mins = e.minutes || 30;
          var end = new Date(start.getTime() + mins * 60000);
          var dom = LifeOS.domain(e.domain);

          count++;
          lines.push('BEGIN:VEVENT');
          lines.push('UID:lifeos-' + e.id + '-' + dayIdx + '-' + slot.key + '@lifeos.local');
          lines.push('DTSTAMP:' + stampUTC(now));
          lines.push('DTSTART:' + stamp(start));
          lines.push('DTEND:' + stamp(end));
          lines.push('RRULE:FREQ=WEEKLY;BYDAY=' + BYDAY[dayIdx] + ';COUNT=' + weeks);
          lines.push(fold('SUMMARY:' + esc(e.title)));
          lines.push(fold('DESCRIPTION:' + esc(dom.label + ' · ' + slot.label +
            ' · scheduled by Life OS. Move or delete it freely — nothing syncs back.')));
          lines.push(fold('CATEGORIES:' + esc(dom.label)));
          lines.push('TRANSP:TRANSPARENT');
          lines.push('END:VEVENT');
        });
      });
    }

    lines.push('END:VCALENDAR');
    return { text: lines.join('\r\n'), events: count, weeks: weeks };
  }

  function download(plan, opts) {
    var made = build(plan, opts);
    var blob = new Blob([made.text], { type: 'text/calendar;charset=utf-8' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'life-os.ics';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
    return made;
  }

  LifeOS.ics = { build: build, download: download };
})(window);
